name: Terraform Destroy

on:
  workflow_dispatch:   # Manual trigger from GitHub UI

jobs:
  destroy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Dev, Prod]   # run destroy for Dev and Prod separately

    # Use environment for optional approvals
    environment: ${{ matrix.environment }}

    defaults:
      run:
        working-directory: Env/${{ matrix.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # change to your region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
